---
title: "sh10050_rna_bulk_script"
author: "Eric Medina"
date: "2023-03-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(edgeR)
library(patchwork)
library(data.table)
library(ggplot2)
library(annotables)
library(RColorBrewer)
library(conflicted)
library(tidyverse)

#CONFLICTS
conflict_prefer_all("dplyr", quiet = T)
conflict_prefer_all("mgcv", losers = "gam", quiet = T)

#Main dir
dir <- "~/u01_rna.seq/sh10050/"

#Strings
cline <- "MCF7"
batch <- "sh10050"
```

```{r}
#SET SEED
set.seed(0310)

#IMPORT COUNTS AND FILTER GENES TO MATCH GRCH38
setwd(paste0(dir, "merged_counts/"))
counts <- read_tsv(file = "SH10050.merged.counts.tsv", quote = "")
dim(counts)
head(counts)[,1:5]

#Get genes with multiple Gene_Symbols (multiple transcripts)
en_ids <- counts %>%
  as.data.frame() %>%
  dplyr::select(Gene_Symbol) %>%
  group_by(Gene_Symbol) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  #slice_head(n = 1000) %>% 
  filter(count > 1) %>% 
  pull(Gene_Symbol) %>% 
  as.character()

counts1 <- counts %>% 
  select(-c(EN_T, EN_G))

#Remove duplicate genes and keep unique genes
counts1.1 <- counts1 %>% 
  filter(!Gene_Symbol %in% en_ids)

#Filter for duplicated genes
counts1.2 <- counts1 %>% 
  filter(Gene_Symbol %in% en_ids)

#For loop to combine counts for duplicated gene symbols (Transcripts)
## (Kallistro output was estimated per transcript)
#i <- "Y_RNA"
#x <- sample(en_ids, 4)
tmp1 <- list()
system.time(
for (i in en_ids) {
#for (i in x) {
  print(i)
  tmp <- counts1.2 %>% 
    as.data.frame() %>% 
    filter(Gene_Symbol == i) %>% 
    select(-Gene_Symbol) %>% 
    colSums() %>% 
    as.data.frame() %>% 
    t() %>% 
    as.data.frame() %>% 
    mutate(Gene_Symbol = i, .before = colnames(.)[1]) %>% 
    remove_rownames()
  
  tmp1[[i]] <- tmp
    
})


#merge list into one dataframe
x2 <- plyr::ldply(tmp1, data.frame, .id = NULL)

colnames(x2) <- colnames(counts1.2)

#Merge with counts with unique names
counts2 <- counts1.1 %>% 
  full_join(x2)

#.f = function() {
setwd(dir = paste0(dir, "counts/filtered"))
write.table(counts2, file = "sh10050_dup.transcripts_combined_counts.txt",
              sep = "\t", col.names = T, row.names = F, quote = F)
#}

#Insert entrezID, filter NAs, match to counts
#Get filtered gene symbols
#remove gene symbols with "ENS"
g.tmp <- counts2 %>%
  select(Gene_Symbol) %>% 
  as.data.frame()
g.tmp1 <- g.tmp[grepl("ENS", g.tmp$Gene_Symbol),]
g <- g.tmp %>% 
  filter(!Gene_Symbol %in% g.tmp1)

dim(g)
head(g, 10)
head(grch38,10)
#Get gene symbols from grch38
annot <- grch38 %>%
  as.matrix() %>% 
  as.data.frame() %>%
  dplyr::rename("Gene_Symbol" = "symbol",
                "ENTREZID" = "entrez",
                "ENZGENE" = "ensgene")
dim(annot)
head(annot, 10)
#Match gene symbols from grch38 to filtered gene symbols
annot2 <- annot[match(g$Gene_Symbol, annot$Gene_Symbol),]
dim(annot2)
head(annot2, 10)
#Remove NAs
sum(is.na(annot2))
annot3 <- na.omit(annot2)
sum(is.na(annot3))

dim(annot3)
dim(counts2)
#Only keep gene symbols in grch38
counts2.1 <- counts2 %>%
  dplyr::filter(Gene_Symbol %in% annot3$Gene_Symbol) %>%
  column_to_rownames(var = "Gene_Symbol")
dim(counts2.1)
sum(is.na(counts2.1))

#CHANGE CODED NAMES IN COUNTS USING KIMYA'S DECODER 
decoder <- openxlsx::read.xlsx(paste0(dir, "sh10050_sample_decoder.xlsx"))

#Clean up names
decoder1 <- decoder %>%
  as.data.frame() %>%
  mutate(Cell.Type2 = Cell.Type,
         Cell.Type2 = gsub("-", "", Cell.Type2)) %>%
  #there were spaces at the end of some of the strings, needed to trim.
  mutate_at(vars(Cell.Type2), str_trim) %>%
  mutate(Cell.Type2 = gsub(" ", "_", Cell.Type2),
         Cell.Type3 = 
           ifelse(Cell.Type2 == "MCF7_Sensitive", "MCF7_Sen", "MCF7_RiboR"),
         Condition2 = 
           ifelse(Condition == "Afatinib", "Afat",
                  ifelse(Condition == "Combo", "Comb",
                         ifelse(Condition == "DMSO", "DMSO",
                                ifelse(Condition == "none", "NT",
                                       ifelse(Condition == "Ribociclib",
                                              "Ribo", "")))))) %>%
  unite(Cell.Type4, c(Cell.Type3, Condition2), sep = "_", remove = F) %>%
  mutate(Time2 = gsub(" ", "_", Time),
         Time2 = gsub("Day", "D", Time2),
         Time2 = gsub("Hr", "H", Time2),
         Time2 = gsub("_", "", Time2)) %>%
  unite(Cell.Type5, c(Cell.Type4, Time2), sep = "_", remove = F) %>%
  separate(Sample.ID, 
           into = c("Sample.num", "Sample.ID"), 
           sep = "[_^]", 
           extra = "merge", 
           remove = F) %>%
  unite(Cell.Type6, c(Sample.num, Cell.Type5), sep = "_", remove = F) %>%
  dplyr::select(Cell.Type6, Cell.Type, Condition, Time, Sample.num, Sample.ID) %>%
  separate(Cell.Type6, 
           into = c("num", "CellLine", "State", "Treatment", "TimePoint"),
           remove = F) %>%
  unite(Sample.ID2, c(Sample.num, Sample.ID), sep = "_", remove = F) %>% 
  unite("S_T", c(State, Treatment), sep = "_", remove = F) %>% 
  unite("S_T_T", c(S_T, TimePoint), sep = "_", remove = F) %>% 
  mutate_at(vars(CellLine, State, Treatment, TimePoint, S_T, S_T_T), as.factor) %>% 
  mutate_at(vars(Sample.num), as.numeric)

#Check as I go
#head(decoder1)
#table(decoder1$Cell.Type2)
#table(decoder1$Cell.Type3)
#table(decoder1$Cell.Type2, decoder1$Cell.Type3)
#table(decoder1$Condition, decoder1$Condition2)
#table(decoder1$Cell.Type3)
#table(decoder1$Time2)

#Confirm names are the same in new decoder
if (all(decoder$Sample.ID == decoder1$Sample.ID2)) {
  print("TRUE")
} else {
  print("FALSE")
}

if (all(decoder1$num == decoder1$Sample.num)) {
  print("TRUE")
} else {
  print("FALSE")
}

#REPLACE CODED NAMES IN COUNTS

#Get names from counts 
names <- colnames(counts2.1)
names <- names %>%
  as.data.frame() %>%
  dplyr::rename("Cell.ID" = ".") %>%
  separate(Cell.ID, into = c("num", "code"), sep = "[_^]", extra = "merge", remove = F)

#Confirm column names in counts2 matrix match order of names$Cell.ID
if (all(names$Cell.ID == colnames(counts2.1))) {
  print("TRUE")
} else {
  print("FALSE")
}

#Rearrange order of decoder to match order of column names in counts2
decoder2 <- decoder1[match(names$num, decoder1$num),]
if (all(decoder2$num == names$num)) {
  print("TRUE")
} else {
  print("FALSE")
}

#Make count matrix with decoded column names
counts3 <- counts2.1
colnames(counts3) <- decoder2$Cell.Type6

#USE EDGER TO NORMALIZE AND FILTER COUNTS

#Determine group size for each sample
## Here used the numbering system from Kimya's decoder for group

#Create edgeR object
y <- DGEList(counts = counts3, group = decoder2$num, genes = annot3)
y

#Insert varibles in object
y$samples$lib.size <- colSums(y$counts)
y$samples$CellLine <- decoder2$CellLine
y$samples$State <- decoder2$State
y$samples$Treatment <- decoder2$Treatment
y$samples$Time <- decoder2$TimePoint
y$samples$S_T <- decoder2$S_T
y$samples$S_T_T <- decoder2$S_T_T

#Relevel/order
y$samples$State <- relevel(y$samples$State, ref = "Sen")
#y$samples$Treatment <- relevel(y$samples$Treatment, ref = "NT")
y$samples$Treatment <- ordered(y$samples$Treatment,
                               levels = c("NT", "DMSO", "Afat", "Ribo", "Comb"))
y$samples$Time <- ordered(y$samples$Time,
                          levels = c("D0H0", "D0H6", "D0H24",
                                     "D6H0", "D6H6", "D6H24", 
                                     "D12H0", "D12H6", "D12H24",
                                     "D18H0", "D18H6", "D18H24"))
y$samples$S_T <- ordered(y$samples$S_T,
                          levels = c("Sen_NT", "RiboR_NT", "Sen_DMSO",
                                     "RiboR_DMSO", "Sen_Afat", "RiboR_Afat", 
                                     "Sen_Ribo", "RiboR_Ribo", "Sen_Comb",
                                     "RiboR_Comb"))

head(data.frame(Sample=colnames(y),y$samples$group, 
                y$samples$CellLine, y$samples$State, 
                y$samples$Treatment, y$samples$Time))

#For graphs: Use logCPM for exploratory plots.
##calculate mean and median cpm cutoffs

L <- mean(y$samples$lib.size) * 1e-6 #average lib size here is ~ 21 million
M <- median(y$samples$lib.size) * 1e-6
c(L, M)

#Minimum number of genes kept in filtering = 10 in minimum number of samples
## (minimum number of samples based on grouping factor)
lcpm.cutoff <- log2(10/M + 2/L) 
nsamples <- ncol(y)

#expand color palette
col <- colorRampPalette(brewer.pal(9, "Set1"))

#Look at Unfiltered logCPM
lcpm.unfilt <- cpm(y, log = T) #log2(cpm + 2/L)
#added to cpm before log2: 2^logcpm - cpm = d; d + cpm = log2(cpm)
cpm.unfilt <- cpm(y, log = F)
counts.unfilt <- y$counts
dim(lcpm.unfilt)
r.lcpm.unf <- nrow(lcpm.unfilt)

#Extra QC plots of unfiltered data
#.f = function() {
summary(lcpm.unfilt)

setwd(dir = paste0(dir, "counts/unfiltered/figures/"))

pdf(file = "sh10050_QC_logCPM_unfiltered_boxplot.pdf")
boxplot(lcpm.unfilt, col = col(nsamples))
title(main="A. Raw data", xlab="Log-cpm")
dev.off()

pdf(file = paste("sh10050_QC_logCPM_unfiltered", r.lcpm.unf,
                 "distribution_test.pdf", sep = "_"), width = 9, height = 6)
plot(density(lcpm.unfilt[,1]), col=col(nsamples), lwd=2, ylim=c(0,0.26), 
     las=2, main="", xlab="")
title(main="Unfiltered data", xlab="Log2CPM")
abline(v=lcpm.cutoff, lty=3)
for (i in 2:nsamples){
den <- density(lcpm.unfilt[,i])
lines(den$x, den$y, col=col(nsamples)[i], lwd=2)
 }
snames <- rownames(y$samples)
legend("topright", snames, text.col=col(nsamples), bty="n", cex = .6)
dev.off()


pdf(file = paste("QC_unfiltered", r.lcpm.unf,
                 "gene_expression_multi.demonsional.scaling_MDS_plot.pdf", 
                 sep = "_"),
    width = 9, height = 6)
plotMDS(lcpm.unfilt, labels = y$samples$S_T_T,
        cex = 0.7, 
        dim.plot = c(1,2))
title(main="Average (root-mean-square) of largest logFC changes")
dev.off()

#Save counts
setwd(dir = paste0(dir, "counts/unfiltered/"))

# Save logCPM unfiltered values
write.table(lcpm.unfilt, file = paste("sh10050_logCPM.unfiltered",
                                      r.lcpm.unf ,"genes.txt", sep = "_"),
            sep = "\t", col.names = T, row.names = T, quote = F)
# Save CPM unfiltered values
write.table(cpm.unfilt, file = paste("sh10050_CPM.unfiltered",
                                     r.lcpm.unf ,"genes.txt", sep = "_"),
            sep = "\t", col.names = T, row.names = T, quote = F)
# Save counts unfiltered values
write.table(counts.unfilt, file = paste("sh10050_counts.unfiltered",
                                        r.lcpm.unf ,"genes.txt", sep = "_"),
            sep = "\t", col.names = T, row.names = T, quote = F)
#}

#Make DF for summary statistics
#Get mean and variance
summ <- counts.unfilt %>% 
#summ <- lcpm.unfilt %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "Gene_Symbol") %>% 
  pivot_longer(!Gene_Symbol, names_to = "Cell.ID", values_to = "lcpm") %>% 
  group_by(Gene_Symbol) %>% 
  summarise(mean = mean(lcpm),
            sd = sd(lcpm),
            var = var(lcpm))
plot(x = summ$mean, y = summ$var)

setwd(dir = paste0(dir, "counts/unfiltered/figures/"))
#ggplot mean vs variance
pdf(file = paste("sh10050_mean_vs_variance_counts_unfiltered.pdf", sep = "_"),
    width = 7, height = 5)
ggplot(summ, mapping = aes(x = log(mean,base = 2), y = log(var,base = 2))) +
  geom_point() +
  ylim(c(9.572694e-31,1.234371e+01)) +
  xlim(c(-3.419904, 13.456157)) +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs")) +
  theme_classic() +
  labs(title = "log2 CPM Mean vs Variance unfiltered")
dev.off()


#FILER EDGER OBJECT FOR LOW EXPRESSED GENES

dim(y)
keep <- filterByExpr(y, group = y$samples$State)
table(keep)
y1 <- y[keep, , keep.lib.sizes = F]
dim(y1)

#TMM library normalization
y1 <- calcNormFactors(y1, method = "TMM")

#Look at filtered logCPM
lcpm.filt <- cpm(y1, log = T)
cpm.filt <- cpm(y1, log = F)
counts.filt <- y1$counts
lcpm.filt[1:5,1:5]
r.lcpm.filt <- nrow(lcpm.filt)
r.lcpm.filt

#.f = function() {
setwd(dir = paste0(dir, "counts/filtered/"))

# SAVE FILTERED LOG2CPM
lcpm.filt_ <- lcpm.filt %>%
  as.data.frame() %>%
  rownames_to_column(var = "gene")
write.table(lcpm.filt_, file = paste("sh10050_logCPM_filtered_normalized",
                                    r.lcpm.filt, "genes.txt",
                                    sep = "_"),
            sep = "\t", col.names = T, row.names = F, quote = F)

cpm.filt_ <- cpm.filt %>%
  as.data.frame() %>%
  rownames_to_column(var = "gene")

# SAVE FILTERED CPM
write.table(cpm.filt_, file = paste("sh10050_CPM_filtered_normalized",
                                   r.lcpm.filt, "genes.txt",
                                   sep = "_"),
            sep = "\t", col.names = T, row.names = T, quote = F)

counts.filt_ <- counts.filt %>%
  as.data.frame() %>%
  rownames_to_column(var = "gene")
# SAVE FILTERED COUNTS
write.table(counts.filt_, file = paste("sh10050_counts_filtered_normalized",
                                      r.lcpm.filt, "genes.txt",
                                      sep = "_"),
            sep = "\t", col.names = T, row.names = T, quote = F)

#}


#Extra QC plots of filtered data

#.f = function() {

summary(lcpm.filt)

setwd(dir = paste0(dir, "counts/filtered/figures/"))

pdf(file = "sh10050_QC_logCPM_filtered_boxplot.pdf")
boxplot(lcpm.filt, col = col(nsamples))
title(main="A. Filtered data", xlab="Log-cpm")
dev.off()

L <- mean(y1$samples$lib.size) * 1e-6 
M <- median(y1$samples$lib.size) * 1e-6
c(L, M)
lcpm.cutoff <- log2(10/M + 2/L)

#Plot filtered library
pdf(file = paste("sh10050_QC_filtered", r.lcpm.filt, 
                 "distribution.pdf", sep = "_"), width = 9, height = 6)
plot(density(lcpm.filt[,1]), col=col(nsamples), lwd=2, ylim=c(0,0.26), las=2, 
     main="", xlab="")
title(main="Filtered data", xlab="Log2CPM")
abline(v=lcpm.cutoff, lty=3)
for (i in 2:nsamples){
den <- density(lcpm.filt[,i])
lines(den$x, den$y, col=col(nsamples)[i], lwd=2)
 }
legend("topright", snames, text.col=col(nsamples), bty="n", cex = .6)
dev.off()

#plot MDS
pdf(file = paste("sh10050_QC_filtered", r.lcpm.filt, "gMDS_plot.pdf", 
                 sep = "_"), width = 9, height = 6)
plotMDS(lcpm.filt, labels = y1$samples$S_T_T, 
        cex = 0.7, 
        dim.plot = c(1,2)
        )
title(main="Average (root-mean-square) of largest logFC changes")
dev.off()

#}

 
#Barplot
pdf(file = paste("sh10050_filtered_library_sizes.pdf",
                 sep = "_"),
    width = 10, height = 6)
barplot(y1$samples$lib.size, 
        names=y1$samples$group, 
        ylab="Library size (Read depth)",
        col = "grey", angle = 45)
title("Normalize Library Size")
abline(h=median(y1$samples$lib.size), col = "red")
dev.off()


#save filtered lib.size for integrated barplot
t <- data.frame(sample = y1$samples$S_T_T,
                group = y1$samples$group,
                lib.size = y1$samples$lib.size,
                norm.factors = y1$samples$norm.factors)

#.f = function() {

#Save
setwd(dir = paste0(dir, "counts/filtered/"))
write.table(t, file = paste("sh10050_filtered_library_sizes.txt", sep = "_"),
            sep = "\t", quote = F, col.names = T, row.names = F)


setwd(dir = paste0(dir, "counts/filtered/figures/"))
pdf(file = paste("sh10050_filtered_library_sizes_ggplot.pdf",
                 sep = "_"),
    width = 10, height = 6)
ggplot(t, mapping = aes(x = sample, y = lib.size, fill = group)) + 
  geom_col() + 
  theme_classic() +
  theme(axis.text.x.bottom = element_text(angle = 35, vjust = .5, face = "bold")) +
  geom_hline(aes(yintercept =  median(lib.size)), color = "red") +
  theme(plot.title = element_text(hjust = .5, face = "bold")) +
  theme(axis.text.x.bottom = element_text(hjust = .4, vjust = .2)) +
  theme(legend.position = "none")
dev.off()

#}


#Make DF for summary statistics
#Get mean and variance
summ1 <- counts.filt %>%
#summ1 <- lcpm.filt %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "Gene_Symbol") %>% 
  pivot_longer(!Gene_Symbol, names_to = "Cell.ID", values_to = "lcpm") %>% 
  group_by(Gene_Symbol) %>% 
  summarise(mean = mean(lcpm),
            sd = sd(lcpm),
            var = var(lcpm))
plot(x = summ1$mean, y = summ1$var)

#ggplot mean vs variance
pdf(file = paste("sh10050_mean_vs_variance_counts_filtered.pdf", sep = "_"),
    width = 7, height = 5)
ggplot(summ1, mapping = aes(x = log(mean,base = 2), y = log(var,base = 2))) +
  geom_point() +
  ylim(c(9.572694e-31,1.234371e+01)) +
  xlim(c(-3.419904, 13.456157)) +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs")) +
  labs(title = "log2 CPM Mean vs Variance filtered") +
  theme_classic()
dev.off()

#MAKE DATAFAME FOR STATISTICAL TESTING
b.log2cpm <- lcpm.filt %>% 
  as.data.frame() %>%
  mutate("1_MCF7_Sen_DMSO_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "1_MCF7_Sen_Afat_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "1_MCF7_Sen_Ribo_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "1_MCF7_Sen_Comb_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "2_MCF7_RiboR_DMSO_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]],
         "2_MCF7_RiboR_Afat_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]],
         "2_MCF7_RiboR_Ribo_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]],
         "2_MCF7_RiboR_Comb_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]]) %>% 
  dplyr::select(-c("1_MCF7_Sen_NT_D0H0", "2_MCF7_RiboR_NT_D0H0")) %>% 
  rownames_to_column(var = "Gene") %>%
  pivot_longer(! Gene, names_to = "Cell", values_to = "Expression.log2cpm")

#
b.cpm <- cpm.filt %>% 
  as.data.frame() %>%
  mutate("1_MCF7_Sen_DMSO_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "1_MCF7_Sen_Afat_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "1_MCF7_Sen_Ribo_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "1_MCF7_Sen_Comb_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "2_MCF7_RiboR_DMSO_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]],
         "2_MCF7_RiboR_Afat_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]],
         "2_MCF7_RiboR_Ribo_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]],
         "2_MCF7_RiboR_Comb_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]]) %>% 
  dplyr::select(-c("1_MCF7_Sen_NT_D0H0", "2_MCF7_RiboR_NT_D0H0")) %>% 
  rownames_to_column(var = "Gene") %>%
  pivot_longer(! Gene, names_to = "Cell", values_to = "Expression.cpm")

#
b.counts <- counts.filt %>% 
  as.data.frame() %>%
  mutate("1_MCF7_Sen_DMSO_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "1_MCF7_Sen_Afat_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "1_MCF7_Sen_Ribo_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "1_MCF7_Sen_Comb_D0H0" = .[["1_MCF7_Sen_NT_D0H0"]],
         "2_MCF7_RiboR_DMSO_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]],
         "2_MCF7_RiboR_Afat_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]],
         "2_MCF7_RiboR_Ribo_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]],
         "2_MCF7_RiboR_Comb_D0H0" = .[["2_MCF7_RiboR_NT_D0H0"]]) %>% 
  dplyr::select(-c("1_MCF7_Sen_NT_D0H0", "2_MCF7_RiboR_NT_D0H0")) %>% 
  rownames_to_column(var = "Gene") %>%
  pivot_longer(! Gene, names_to = "Cell", values_to = "Expression.counts")

#Make data frame
b.data <- data.frame("Gene" = b.counts$Gene,
                     "Cell" = b.counts$Cell,
                     "Expression.counts" = b.counts$Expression.counts,
                     "Expression.cpm" = b.cpm$Expression.cpm,
                     "Expression.log2cpm" = b.log2cpm$Expression.log2cpm)
#Change some names
b.data1 <- b.data %>%
  as.matrix() %>%
  as.data.frame() %>%
  separate(Cell, into = c("num", "CellLine", "State", "Treatment", "Time"),
           sep = "_", remove = F) %>%
  unite(S_T, c(State, Treatment), sep = "_", remove = F) %>%
  unite(S_T_T, c(State, Treatment, Time), sep = "_", remove = F) %>%
  dplyr::select(Gene, Expression.counts, Expression.cpm, Expression.log2cpm,
                Cell, CellLine, S_T, S_T_T, State, Treatment, Time, num) %>% 
  mutate(Hour = ifelse(Time == "D0H0", 0,
                ifelse(Time == "D0H6", 6,
                ifelse(Time == "D0H24", 24,
                ifelse(Time == "D6H0", 144,
                ifelse(Time == "D6H6", 150,
                ifelse(Time == "D6H24", 168,
                ifelse(Time == "D12H0", 288,
                ifelse(Time == "D12H6", 294,
                ifelse(Time == "D12H24", 312,
                ifelse(Time == "D18H0", 432,
                ifelse(Time == "D18H6", 438,
                ifelse(Time == "D18H24", 456, ""))))))))))))) %>% 
  mutate_at(vars(Gene, CellLine, Cell, S_T, S_T_T, Treatment, State, Time),
            as.factor) %>% 
  mutate_at(vars(Expression.counts, Expression.cpm, Expression.log2cpm),
            as.numeric) %>% 
  mutate_at(vars(Hour), as.integer)
  
b.data1$Time <- ordered(b.data1$Time,
                            levels = c("D0H0", 
                                       "D0H6",
                                       "D0H24",
                                       "D6H0", "D6H6", "D6H24", 
                                       "D12H0", "D12H6", "D12H24", 
                                       "D18H0", 
                                       "D18H6",
                                      "D18H24"))
str(b.data1)

#.f = function() {
#SAVE DATAFRAME FOR STATISTICAL TESTING
setwd(paste0(dir, "gam/"))
write.table(b.data1, file = "sh10050_model_format_counts_post_filter.txt",
            sep = "\t", col.names = T, row.names = F, quote = F)
#}
```